/*
 * @Author: KokoTa
 * @Date: 2020-08-10 17:30:16
 * @LastEditTime: 2020-08-15 11:14:33
 * @LastEditors: KokoTa
 * @Description:
 * @FilePath: /AwesomeProject/js/MainApp/action/type.js
 */
const Type = {
  // 最热页
  POPULAR_REFRESH: 'POPULAR_REFRESH',
  POPULAR_REFRESH_FAIL: 'POPULAR_REFRESH_FAIL',
  POPULAR_REFRESH_SUCCESS: 'POPULAR_REFRESH_SUCCESS',
  POPULAR_LOAD_MORE_REFRESH: 'POPULAR_LOAD_MORE_REFRESH',
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS',
  // 趋势页
  TRENDING_REFRESH: 'TRENDING_REFRESH',
  TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL',
  TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',
  DEVICE_EMIT_TIME_SPAN_CHANGE: 'DEVICE_EMIT_TIME_SPAN_CHANGE',
  // 最热页和趋势页的收藏功能
  POPULAR_FAVORITE_CHANGE: 'POPULAR_FAVORITE_CHANGE',
  TRENDING_FAVORITE_CHANGE: 'TRENDING_FAVORITE_CHANGE',
  // 收藏页
  FAVORITE_LOAD: 'FAVORITE_LOAD',
  FAVORITE_LOAD_SUCCESS: 'FAVORITE_LOAD_SUCCESS',
  FAVORITE_LOAD_FAIL: 'FAVORITE_LOAD_FAIL',
};

export default Type;
